package itee.licenta.monitorizare.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppointmentSlotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppointmentSlotAllPropertiesEquals(AppointmentSlot expected, AppointmentSlot actual) {
        assertAppointmentSlotAutoGeneratedPropertiesEquals(expected, actual);
        assertAppointmentSlotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppointmentSlotAllUpdatablePropertiesEquals(AppointmentSlot expected, AppointmentSlot actual) {
        assertAppointmentSlotUpdatableFieldsEquals(expected, actual);
        assertAppointmentSlotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppointmentSlotAutoGeneratedPropertiesEquals(AppointmentSlot expected, AppointmentSlot actual) {
        assertThat(actual)
            .as("Verify AppointmentSlot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppointmentSlotUpdatableFieldsEquals(AppointmentSlot expected, AppointmentSlot actual) {
        assertThat(actual)
            .as("Verify AppointmentSlot relevant properties")
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getIsAvailable()).as("check isAvailable").isEqualTo(expected.getIsAvailable()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppointmentSlotUpdatableRelationshipsEquals(AppointmentSlot expected, AppointmentSlot actual) {
        assertThat(actual)
            .as("Verify AppointmentSlot relationships")
            .satisfies(a -> assertThat(a.getDoctor()).as("check doctor").isEqualTo(expected.getDoctor()));
    }
}
