package itee.licenta.monitorizare.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MedicalDataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalDataAllPropertiesEquals(MedicalData expected, MedicalData actual) {
        assertMedicalDataAutoGeneratedPropertiesEquals(expected, actual);
        assertMedicalDataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalDataAllUpdatablePropertiesEquals(MedicalData expected, MedicalData actual) {
        assertMedicalDataUpdatableFieldsEquals(expected, actual);
        assertMedicalDataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalDataAutoGeneratedPropertiesEquals(MedicalData expected, MedicalData actual) {
        assertThat(actual)
            .as("Verify MedicalData auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalDataUpdatableFieldsEquals(MedicalData expected, MedicalData actual) {
        assertThat(actual)
            .as("Verify MedicalData relevant properties")
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()))
            .satisfies(a -> assertThat(a.getHeartRate()).as("check heartRate").isEqualTo(expected.getHeartRate()))
            .satisfies(a -> assertThat(a.getSpo2()).as("check spo2").isEqualTo(expected.getSpo2()))
            .satisfies(a -> assertThat(a.getTemperature()).as("check temperature").isEqualTo(expected.getTemperature()))
            .satisfies(a -> assertThat(a.getSystolicBp()).as("check systolicBp").isEqualTo(expected.getSystolicBp()))
            .satisfies(a -> assertThat(a.getDiastolicBp()).as("check diastolicBp").isEqualTo(expected.getDiastolicBp()))
            .satisfies(a -> assertThat(a.getHrv()).as("check hrv").isEqualTo(expected.getHrv()))
            .satisfies(a -> assertThat(a.getQtInterval()).as("check qtInterval").isEqualTo(expected.getQtInterval()))
            .satisfies(a -> assertThat(a.getBnp()).as("check bnp").isEqualTo(expected.getBnp()))
            .satisfies(a -> assertThat(a.getBloodGlucose()).as("check bloodGlucose").isEqualTo(expected.getBloodGlucose()))
            .satisfies(a -> assertThat(a.getRespiratoryRate()).as("check respiratoryRate").isEqualTo(expected.getRespiratoryRate()))
            .satisfies(a -> assertThat(a.getFev1()).as("check fev1").isEqualTo(expected.getFev1()))
            .satisfies(a -> assertThat(a.getEtco2()).as("check etco2").isEqualTo(expected.getEtco2()))
            .satisfies(a -> assertThat(a.getAnomalyScore()).as("check anomalyScore").isEqualTo(expected.getAnomalyScore()))
            .satisfies(a -> assertThat(a.getIsAnomaly()).as("check isAnomaly").isEqualTo(expected.getIsAnomaly()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalDataUpdatableRelationshipsEquals(MedicalData expected, MedicalData actual) {
        assertThat(actual)
            .as("Verify MedicalData relationships")
            .satisfies(a -> assertThat(a.getPatient()).as("check patient").isEqualTo(expected.getPatient()));
    }
}
